import {ModeCategory} from "../../Models/Enums/ModeCategory.ts";

export var availableModes = [
{id:1, name:'Ocean', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:2, name:'Romance', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:3, name:'Sunset', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:4, name:'Party', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:5, name:'Fireplace', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:6, name:'Cozy', speedChange: false, brightnessChange: true, category: ModeCategory.FUNCTIONAL},
{id:7, name:'Forest', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:8, name:'Pastel Colors', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:9, name:'Wake-Up', speedChange: false, brightnessChange: false, category: ModeCategory.PROGRESSIVE},
{id:10, name:'Bedtime', speedChange: false, brightnessChange: true, category: ModeCategory.PROGRESSIVE},
{id:11, name:'Warm White', speedChange: false, brightnessChange: true, category: ModeCategory.BASIC},
{id:12, name:'Daylight', speedChange: false, brightnessChange: true, category: ModeCategory.BASIC},
{id:13, name:'Cool White', speedChange: false, brightnessChange: true, category: ModeCategory.BASIC},
{id:14, name:'Night Light', speedChange: false, brightnessChange: false, category: ModeCategory.FUNCTIONAL},
{id:15, name:'Focus', speedChange: false, brightnessChange: true, category: ModeCategory.FUNCTIONAL},
{id:16, name:'Relax', speedChange: false, brightnessChange: true, category: ModeCategory.FUNCTIONAL},
{id:17, name:'True Colors', speedChange: false, brightnessChange: true, category: ModeCategory.FUNCTIONAL},
{id:18, name:'TV Time', speedChange: false, brightnessChange: true, category: ModeCategory.FUNCTIONAL},
{id:19, name:'Plant Growth', speedChange: false, brightnessChange: true, category: ModeCategory.FUNCTIONAL},
{id:20, name:'Spring', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:21, name:'Summer', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:22, name:'Fall', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:23, name:'Deep Dive', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:24, name:'Jungle', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:25, name:'Mojito', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:26, name:'Club', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:27, name:'Christmas', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:28, name:'Halloween', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:29, name:'Candlelight', speedChange: false, brightnessChange: true, category: ModeCategory.WHITE},
{id:30, name:'Golden White', speedChange: true, brightnessChange: true, category: ModeCategory.WHITE},
{id:31, name:'Pulse', speedChange: true, brightnessChange: true, category: ModeCategory.WHITE},
{id:32, name:'Steampunk', speedChange: true, brightnessChange: true, category: ModeCategory.WHITE},
{id:33, name:'Diwali', speedChange: true, brightnessChange: true, category: ModeCategory.COLOR},
{id:35, name:'Alarm', speedChange: false, brightnessChange: false, category: ModeCategory.WHITE}
]